CREATE TABLE RNUM(
    NO_SQ NUMBER,
    NAME VARCHAR2(100)
);

INSERT INTO RNUM VALUES (2, '±Ë¿≤');

SELECT * FROM RNUM;

SELECT ROWNUM, A.* FROM RNUM A;

SELECT 
    ROW_NUMBER() OVER(PARTITION BY NO_SQ ORDER BY NAME ASC) AS RNUM,
    NO_SQ, 
    NAME 
FROM RNUM
--ORDER BY NAME DESC
;

CREATE TABLE FI_DOCU_MST(
    DOCU_NO VARCHAR(200),
    DOCU_SQ NUMBER,
    DOCU_AMT NUMBER
);    

INSERT INTO FI_DOCU_MST VALUES('1', 1, 1000);
INSERT INTO FI_DOCU_MST VALUES('1', 2, 400);
INSERT INTO FI_DOCU_MST VALUES('1', 3, 300);
INSERT INTO FI_DOCU_MST VALUES('1', 4, 400);
INSERT INTO FI_DOCU_MST VALUES('1', 5, 500);
INSERT INTO FI_DOCU_MST VALUES('2', 3, 500);
INSERT INTO FI_DOCU_MST VALUES('2', 2, 500);
INSERT INTO FI_DOCU_MST VALUES('2', 1, 400);


SELECT * FROM FI_DOCU_MST;

CREATE TABLE HR_EMP_MST(
    ID VARCHAR2(100) PRIMARY KEY,
    PW VARCHAR2(1000),
    NAME VARCHAR2(100)
);


SELECT * FROM HR_EMP_MST;

INSERT INTO HR_EMP_MST VALUES ('KDW0725','RLAEHDDNR12','§°§ß§∑');
INSERT INTO HR_EMP_MST VALUES ('KIMDW0725','RLAEHDDNR12','§°§ß§∑');

COMMIT;

SELECT ID, NAME FROM HR_EMP_MST WHERE ID = 'KDW0725' AND PW = 'RLAEHDDNR12';

SELECT COUNT(1) FROM HR_EMP_MST WHERE ID = 'KIMDW0725'

